-- ============================================================
-- Migration 8: Fix kunci jawaban bocor
--
-- Masalah: siswa bisa akses kolom kunci_jawaban di bank_soal
-- Solusi:
--   1. Buat tabel kunci_jawaban terpisah (RLS deny all anon)
--   2. Migrasi data kunci_jawaban dari bank_soal ke tabel baru
--   3. Buat VIEW bank_soal_siswa (tanpa kolom kunci_jawaban)
--   4. Trigger sync otomatis bank_soal.kunci_jawaban ↔ kunci_jawaban table
--   5. Re-add kolom kunci_jawaban ke bank_soal (admin tetap bisa akses via service_role)
--   6. Revoke SELECT bank_soal dari anon, grant SELECT ke view
-- ============================================================

-- 1. Buat tabel kunci_jawaban (RLS deny all anon)
CREATE TABLE IF NOT EXISTS kunci_jawaban (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bank_soal_id    BIGINT NOT NULL REFERENCES bank_soal(id) ON DELETE CASCADE,
    kunci_jawaban   TEXT,
    created_at      TIMESTAMPTZ DEFAULT now(),
    CONSTRAINT uk_bank_soal_id UNIQUE (bank_soal_id)
);

ALTER TABLE kunci_jawaban ENABLE ROW LEVEL SECURITY;

-- Hapus policy lama (safe re-run)
DROP POLICY IF EXISTS "kunci_jawaban_no_access" ON kunci_jawaban;
CREATE POLICY "kunci_jawaban_no_access" ON kunci_jawaban
    FOR ALL
    TO anon
    USING (false)
    WITH CHECK (false);

REVOKE ALL ON kunci_jawaban FROM anon;
GRANT ALL ON kunci_jawaban TO service_role;

-- 2. Migrasi data dari bank_soal ke kunci_jawaban (idempotent)
INSERT INTO kunci_jawaban (bank_soal_id, kunci_jawaban)
SELECT id, kunci_jawaban FROM bank_soal
WHERE kunci_jawaban IS NOT NULL
  AND id NOT IN (SELECT bank_soal_id FROM kunci_jawaban)
ON CONFLICT (bank_soal_id) DO NOTHING;

-- 3. Buat VIEW bank_soal_siswa (tanpa kunci_jawaban)
CREATE OR REPLACE VIEW bank_soal_siswa AS
SELECT id, pertanyaan, opsi_a, opsi_b, opsi_c, opsi_d, opsi_e, tipe_soal, mapel
FROM bank_soal;

-- 4. Trigger sync otomatis
CREATE OR REPLACE FUNCTION trg_sync_kunci_jawaban_func()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
    IF TG_OP = 'INSERT' OR TG_OP = 'UPDATE' THEN
        INSERT INTO kunci_jawaban (bank_soal_id, kunci_jawaban)
        VALUES (NEW.id, NEW.kunci_jawaban)
        ON CONFLICT (bank_soal_id)
        DO UPDATE SET kunci_jawaban = EXCLUDED.kunci_jawaban;
        RETURN NEW;
    ELSIF TG_OP = 'DELETE' THEN
        DELETE FROM kunci_jawaban WHERE bank_soal_id = OLD.id;
        RETURN OLD;
    END IF;
END;
$$;

DROP TRIGGER IF EXISTS trg_sync_kunci_jawaban ON bank_soal;
CREATE TRIGGER trg_sync_kunci_jawaban
    AFTER INSERT OR UPDATE OR DELETE ON bank_soal
    FOR EACH ROW
    EXECUTE FUNCTION trg_sync_kunci_jawaban_func();

-- 5. Re-add kolom kunci_jawaban ke bank_soal (untuk admin compatibility via service_role)
-- (Jika sudah ada, biarkan saja)
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_name = 'bank_soal' AND column_name = 'kunci_jawaban'
    ) THEN
        ALTER TABLE bank_soal ADD COLUMN kunci_jawaban TEXT;
    END IF;
END $$;

-- 6. Revoke SELECT bank_soal dari anon, grant SELECT ke view
REVOKE SELECT ON bank_soal FROM anon;
GRANT SELECT ON bank_soal_siswa TO anon;

-- 7. Grant INSERT on error_logs (jika ter-revoke)
GRANT INSERT ON error_logs TO anon;
