-- ============================================================
-- Migration 8: Fix kunci jawaban bocor
--
-- Masalah: siswa bisa akses kolom kunci_jawaban di bank_soal
-- Solusi:
--   1. Buat tabel kunci_jawaban terpisah (RLS deny all anon)
--   2. Migrasi data kunci_jawaban dari bank_soal ke tabel baru
--   3. Buat VIEW bank_soal_siswa (tanpa kolom kunci_jawaban)
--   4. Trigger sync otomatis bank_soal.kunci_jawaban ↔ kunci_jawaban table
--   5. Re-add kolom kunci_jawaban ke bank_soal (admin tetap bisa akses via service_role)
--   6. Revoke SELECT bank_soal dari anon, grant SELECT ke view
-- ============================================================

-- 1. Buat tabel kunci_jawaban (RLS deny all anon)
-- Adaptif: jika sudah ada dengan skema berbeda (mis: id_soal alih-alih bank_soal_id), kita sesuaikan
DO $$
DECLARE
    v_fk_column TEXT;
    v_has_bank_soal_id BOOLEAN;
    v_has_id_soal BOOLEAN;
    v_count INT;
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_tables WHERE tablename = 'kunci_jawaban') THEN
        -- Buat dari awal
        CREATE TABLE kunci_jawaban (
            id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            bank_soal_id    BIGINT NOT NULL REFERENCES bank_soal(id) ON DELETE CASCADE,
            kunci_jawaban   TEXT,
            created_at      TIMESTAMPTZ DEFAULT now(),
            CONSTRAINT uk_bank_soal_id UNIQUE (bank_soal_id)
        );
    ELSE
        -- Deteksi kolom FK yang sudah ada
        SELECT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'kunci_jawaban' AND column_name = 'bank_soal_id') INTO v_has_bank_soal_id;
        SELECT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'kunci_jawaban' AND column_name = 'id_soal') INTO v_has_id_soal;

        -- Tambah kolom yang belum ada
        IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'kunci_jawaban' AND column_name = 'kunci_jawaban') THEN
            ALTER TABLE kunci_jawaban ADD COLUMN kunci_jawaban TEXT;
        END IF;
        IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'kunci_jawaban' AND column_name = 'created_at') THEN
            ALTER TABLE kunci_jawaban ADD COLUMN created_at TIMESTAMPTZ DEFAULT now();
        END IF;

        -- Pastikan unique constraint pada FK column yang ada
        IF v_has_bank_soal_id AND NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'uk_bank_soal_id') THEN
            ALTER TABLE kunci_jawaban ADD CONSTRAINT uk_bank_soal_id UNIQUE (bank_soal_id);
        ELSIF v_has_id_soal AND NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'uk_id_soal') THEN
            ALTER TABLE kunci_jawaban ADD CONSTRAINT uk_id_soal UNIQUE (id_soal);
        END IF;

        -- pastikan RLS on
        ALTER TABLE kunci_jawaban ENABLE ROW LEVEL SECURITY;
    END IF;
END $$;

-- RLS policies (jalan di luar DO block karena bisa dipanggil independent)
ALTER TABLE kunci_jawaban ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "kunci_jawaban_no_access" ON kunci_jawaban;
CREATE POLICY "kunci_jawaban_no_access" ON kunci_jawaban
    FOR ALL
    TO anon
    USING (false)
    WITH CHECK (false);

REVOKE ALL ON kunci_jawaban FROM anon;
GRANT ALL ON kunci_jawaban TO service_role;

-- 2. Migrasi data dari bank_soal ke kunci_jawaban (idempotent)
-- Deteksi kolom FK mana yang dipakai
DO $$
DECLARE
    v_fk_col TEXT;
BEGIN
    SELECT column_name INTO v_fk_col
    FROM information_schema.columns
    WHERE table_name = 'kunci_jawaban'
      AND column_name IN ('bank_soal_id', 'id_soal')
    ORDER BY column_name
    LIMIT 1;

    IF v_fk_col IS NOT NULL THEN
        EXECUTE format(
            'INSERT INTO kunci_jawaban (%I, kunci_jawaban)
             SELECT b.id, b.kunci_jawaban FROM bank_soal b
             WHERE b.kunci_jawaban IS NOT NULL
               AND NOT EXISTS (SELECT 1 FROM kunci_jawaban kj WHERE kj.%I = b.id)
             ON CONFLICT (%I) DO NOTHING',
            v_fk_col, v_fk_col, v_fk_col
        );
    END IF;
END $$;

-- 3. Buat VIEW bank_soal_siswa (tanpa kunci_jawaban)
CREATE OR REPLACE VIEW bank_soal_siswa AS
SELECT id, pertanyaan, opsi_a, opsi_b, opsi_c, opsi_d, opsi_e, tipe_soal, mapel
FROM bank_soal;

-- 4. Trigger sync otomatis (adaptif terhadap nama kolom FK)
CREATE OR REPLACE FUNCTION trg_sync_kunci_jawaban_func()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
    v_fk_col TEXT;
BEGIN
    -- Deteksi kolom FK yang tersedia di tabel kunci_jawaban
    SELECT column_name INTO v_fk_col
    FROM information_schema.columns
    WHERE table_name = 'kunci_jawaban'
      AND column_name IN ('bank_soal_id', 'id_soal')
    ORDER BY column_name
    LIMIT 1;

    IF v_fk_col IS NULL THEN
        RAISE EXCEPTION 'No FK column found in kunci_jawaban table';
    END IF;

    IF TG_OP = 'INSERT' OR TG_OP = 'UPDATE' THEN
        EXECUTE format(
            'INSERT INTO kunci_jawaban (%I, kunci_jawaban) VALUES ($1, $2)
             ON CONFLICT (%I) DO UPDATE SET kunci_jawaban = EXCLUDED.kunci_jawaban',
            v_fk_col, v_fk_col
        ) USING NEW.id, NEW.kunci_jawaban;
        RETURN NEW;
    ELSIF TG_OP = 'DELETE' THEN
        EXECUTE format(
            'DELETE FROM kunci_jawaban WHERE %I = $1',
            v_fk_col
        ) USING OLD.id;
        RETURN OLD;
    END IF;
END;
$$;

DROP TRIGGER IF EXISTS trg_sync_kunci_jawaban ON bank_soal;
CREATE TRIGGER trg_sync_kunci_jawaban
    AFTER INSERT OR UPDATE OR DELETE ON bank_soal
    FOR EACH ROW
    EXECUTE FUNCTION trg_sync_kunci_jawaban_func();

-- 5. Re-add kolom kunci_jawaban ke bank_soal (untuk admin compatibility via service_role)
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_name = 'bank_soal' AND column_name = 'kunci_jawaban'
    ) THEN
        ALTER TABLE bank_soal ADD COLUMN kunci_jawaban TEXT;
    END IF;
END $$;

-- 6. Revoke SELECT bank_soal dari anon, grant SELECT ke view
REVOKE SELECT ON bank_soal FROM anon;
GRANT SELECT ON bank_soal_siswa TO anon;

-- 7. Grant INSERT on error_logs (jika ter-revoke)
GRANT INSERT ON error_logs TO anon;
