-- ============================================================
-- Migration 9: Create nilai_siswa table (was manual only)
-- 
-- Tabel ini dibuat manual via Supabase Dashboard sebelumnya
-- tanpa migration file → risk of data loss on DB reset.
-- Migration ini mendefinisikan ulang tabel + RLS.
-- ============================================================

-- Hapus policy lama sebelum CREATE OR REPLACE
DROP POLICY IF EXISTS "nilai_siswa_no_access" ON nilai_siswa;

-- Buat tabel jika belum ada
-- Adaptif: jika sudah ada, pastikan kolom yang diperlukan ada
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_tables WHERE tablename = 'nilai_siswa') THEN
        CREATE TABLE nilai_siswa (
            id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            nama            TEXT NOT NULL,
            kelas           TEXT NOT NULL,
            mapel           TEXT NOT NULL,
            skor_pg         BIGINT DEFAULT 0,
            durasi          TEXT DEFAULT '-',
            pelanggaran     BIGINT DEFAULT 0,
            status          TEXT DEFAULT 'SELESAI',
            created_at      TIMESTAMPTZ DEFAULT now()
        );
    ELSE
        -- Tambah kolom yang belum ada
        IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'nilai_siswa' AND column_name = 'mapel') THEN
            ALTER TABLE nilai_siswa ADD COLUMN mapel TEXT NOT NULL DEFAULT '';
        END IF;
        IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'nilai_siswa' AND column_name = 'skor_pg') THEN
            ALTER TABLE nilai_siswa ADD COLUMN skor_pg BIGINT DEFAULT 0;
        END IF;
        IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'nilai_siswa' AND column_name = 'durasi') THEN
            ALTER TABLE nilai_siswa ADD COLUMN durasi TEXT DEFAULT '-';
        END IF;
        IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'nilai_siswa' AND column_name = 'pelanggaran') THEN
            ALTER TABLE nilai_siswa ADD COLUMN pelanggaran BIGINT DEFAULT 0;
        END IF;
        IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'nilai_siswa' AND column_name = 'status') THEN
            ALTER TABLE nilai_siswa ADD COLUMN status TEXT DEFAULT 'SELESAI';
        END IF;
        IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'nilai_siswa' AND column_name = 'created_at') THEN
            ALTER TABLE nilai_siswa ADD COLUMN created_at TIMESTAMPTZ DEFAULT now();
        END IF;
    END IF;
END $$;

-- Enable RLS (untuk jaga-jaga jika sebelumnya off)
ALTER TABLE nilai_siswa ENABLE ROW LEVEL SECURITY;

-- Revoke all from anon (jaga-jaga jika default privilege berubah)
REVOKE ALL ON nilai_siswa FROM anon;

-- Policy: deny all for anon
CREATE POLICY "nilai_siswa_no_access" ON nilai_siswa
    FOR ALL
    TO anon
    USING (false)
    WITH CHECK (false);

-- Grant akses ke service_role (untuk admin proxy)
GRANT ALL ON nilai_siswa TO service_role;

-- Index untuk pencarian cepat (sama seperti jawaban_ujian)
-- Pake DO block biar tidak error jika kolom belum ada pas CREATE INDEX
DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'nilai_siswa' AND column_name = 'mapel') THEN
        CREATE INDEX IF NOT EXISTS idx_nilai_siswa_nama_kelas_mapel ON nilai_siswa(nama, kelas, mapel);
    END IF;
    CREATE INDEX IF NOT EXISTS idx_nilai_siswa_created_at ON nilai_siswa(created_at DESC);
END $$;
