-- ============================================================
-- Migration 9: Create nilai_siswa table (was manual only)
-- 
-- Tabel ini dibuat manual via Supabase Dashboard sebelumnya
-- tanpa migration file → risk of data loss on DB reset.
-- Migration ini mendefinisikan ulang tabel + RLS.
-- ============================================================

-- Hapus policy lama sebelum CREATE OR REPLACE
DROP POLICY IF EXISTS "nilai_siswa_no_access" ON nilai_siswa;

-- Buat tabel jika belum ada (safe for re-run)
CREATE TABLE IF NOT EXISTS nilai_siswa (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nama            TEXT NOT NULL,
    kelas           TEXT NOT NULL,
    mapel           TEXT NOT NULL,
    skor_pg         BIGINT DEFAULT 0,
    durasi          TEXT DEFAULT '-',
    pelanggaran     BIGINT DEFAULT 0,
    status          TEXT DEFAULT 'SELESAI',
    created_at      TIMESTAMPTZ DEFAULT now()
);

-- Enable RLS (untuk jaga-jaga jika sebelumnya off)
ALTER TABLE nilai_siswa ENABLE ROW LEVEL SECURITY;

-- Revoke all from anon (jaga-jaga jika default privilege berubah)
REVOKE ALL ON nilai_siswa FROM anon;

-- Policy: deny all for anon
CREATE POLICY "nilai_siswa_no_access" ON nilai_siswa
    FOR ALL
    TO anon
    USING (false)
    WITH CHECK (false);

-- Grant akses ke service_role (untuk admin proxy)
GRANT ALL ON nilai_siswa TO service_role;

-- Index untuk pencarian cepat (sama seperti jawaban_ujian)
CREATE INDEX IF NOT EXISTS idx_nilai_siswa_nama_kelas_mapel ON nilai_siswa(nama, kelas, mapel);
CREATE INDEX IF NOT EXISTS idx_nilai_siswa_created_at ON nilai_siswa(created_at DESC);
